/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/review` | `/review`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/salesforce` | `/salesforce`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sanFrancisco` | `/sanFrancisco`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/review` | `/review`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/salesforce` | `/salesforce`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sanFrancisco` | `/sanFrancisco`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/review${`?${string}` | `#${string}` | ''}` | `/review${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/salesforce${`?${string}` | `#${string}` | ''}` | `/salesforce${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sanFrancisco${`?${string}` | `#${string}` | ''}` | `/sanFrancisco${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/review` | `/review`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/salesforce` | `/salesforce`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sanFrancisco` | `/sanFrancisco`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
